-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema barbearia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema barbearia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `barbearia` DEFAULT CHARACTER SET utf8 ;
USE `barbearia` ;

-- -----------------------------------------------------
-- Table `barbearia`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`clientes` (
  `idclientes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idclientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbearia`.`barbeiros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`barbeiros` (
  `idbarbeiros` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `data_contrat` DATE NOT NULL,
  PRIMARY KEY (`idbarbeiros`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbearia`.`adm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`adm` (
  `idadm` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idadm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbearia`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`especialidades` (
  `idespecialidades` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idespecialidades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbearia`.`barbeiros_especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`barbeiros_especialidades` (
  `idbarbeiros` INT NOT NULL,
  `idespecialidades` INT NOT NULL,
  PRIMARY KEY (`idbarbeiros`, `idespecialidades`),
  INDEX `fk_barbeiros_has_especialidades_especialidades1_idx` (`idespecialidades` ASC) VISIBLE,
  INDEX `fk_barbeiros_has_especialidades_barbeiros_idx` (`idbarbeiros` ASC) VISIBLE,
  CONSTRAINT `fk_barbeiros_has_especialidades_barbeiros`
    FOREIGN KEY (`idbarbeiros`)
    REFERENCES `barbearia`.`barbeiros` (`idbarbeiros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_barbeiros_has_especialidades_especialidades1`
    FOREIGN KEY (`idespecialidades`)
    REFERENCES `barbearia`.`especialidades` (`idespecialidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbearia`.`agendamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`agendamentos` (
  `idagendamentos` INT NOT NULL AUTO_INCREMENT,
  `idclientes` INT NOT NULL,
  `idbarbeiros` INT NOT NULL,
  `idespecialidades` INT NOT NULL,
  `data` DATE NOT NULL,
  `horario` TIME NOT NULL,
  PRIMARY KEY (`idagendamentos`),
  INDEX `fk_agendamentos_clientes1_idx` (`idclientes` ASC) VISIBLE,
  INDEX `fk_agendamentos_barbeiros1_idx` (`idbarbeiros` ASC) VISIBLE,
  INDEX `fk_agendamentos_especialidades1_idx` (`idespecialidades` ASC) VISIBLE,
  CONSTRAINT `fk_agendamentos_clientes1`
    FOREIGN KEY (`idclientes`)
    REFERENCES `barbearia`.`clientes` (`idclientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agendamentos_barbeiros1`
    FOREIGN KEY (`idbarbeiros`)
    REFERENCES `barbearia`.`barbeiros` (`idbarbeiros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agendamentos_especialidades1`
    FOREIGN KEY (`idespecialidades`)
    REFERENCES `barbearia`.`especialidades` (`idespecialidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
