-- MySQL Script generated by MySQL Workbench
-- Mon Aug  5 17:03:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema barbearia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema barbearia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `barbearia` DEFAULT CHARACTER SET utf8mb3 ;
USE `barbearia` ;

-- -----------------------------------------------------
-- Table `barbearia`.`adm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`adm` (
  `idadm` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idadm`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `barbearia`.`barbeiros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`barbeiros` (
  `idbarbeiros` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `data_contrat` DATE NOT NULL,
  PRIMARY KEY (`idbarbeiros`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `barbearia`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`clientes` (
  `idclientes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idclientes`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `barbearia`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`especialidades` (
  `idespecialidades` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idespecialidades`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `barbearia`.`agendamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`agendamentos` (
  `idagendamentos` INT NOT NULL AUTO_INCREMENT,
  `idclientes` INT NOT NULL,
  `idbarbeiros` INT NOT NULL,
  `idespecialidades` INT NOT NULL,
  `data` DATE NOT NULL,
  `horario` TIME NOT NULL,
  PRIMARY KEY (`idagendamentos`),
  INDEX `fk_agendamentos_clientes1_idx` (`idclientes` ASC) VISIBLE,
  INDEX `fk_agendamentos_barbeiros1_idx` (`idbarbeiros` ASC) VISIBLE,
  INDEX `fk_agendamentos_especialidades1_idx` (`idespecialidades` ASC) VISIBLE,
  CONSTRAINT `fk_agendamentos_barbeiros1`
    FOREIGN KEY (`idbarbeiros`)
    REFERENCES `barbearia`.`barbeiros` (`idbarbeiros`),
  CONSTRAINT `fk_agendamentos_clientes1`
    FOREIGN KEY (`idclientes`)
    REFERENCES `barbearia`.`clientes` (`idclientes`),
  CONSTRAINT `fk_agendamentos_especialidades1`
    FOREIGN KEY (`idespecialidades`)
    REFERENCES `barbearia`.`especialidades` (`idespecialidades`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `barbearia`.`barbeiros_especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia`.`barbeiros_especialidades` (
  `idbarbeiros` INT NOT NULL,
  `idespecialidades` INT NOT NULL,
  PRIMARY KEY (`idbarbeiros`, `idespecialidades`),
  INDEX `fk_barbeiros_has_especialidades_especialidades1_idx` (`idespecialidades` ASC) VISIBLE,
  INDEX `fk_barbeiros_has_especialidades_barbeiros_idx` (`idbarbeiros` ASC) VISIBLE,
  CONSTRAINT `fk_barbeiros_has_especialidades_barbeiros`
    FOREIGN KEY (`idbarbeiros`)
    REFERENCES `barbearia`.`barbeiros` (`idbarbeiros`),
  CONSTRAINT `fk_barbeiros_has_especialidades_especialidades1`
    FOREIGN KEY (`idespecialidades`)
    REFERENCES `barbearia`.`especialidades` (`idespecialidades`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO clientes(nome, email, senha) VALUES ("Ricardo", "ricardo@email.com", "1234");
INSERT INTO barbeiros(nome, data_nasc, data_contrat) VALUES ("Adriano", '2000-08-05', '2024-08-05');
INSERT INTO especialidades(nome) VALUES ("barba"), ("tesoura"), ("sobrancelha");
INSERT INTO barbeiros_especialidades(idbarbeiros, idespecialidades) VALUES (1, 1);
INSERT INTO agendamentos(idclientes, idbarbeiros, idespecialidades, data, horario) VALUES (1, 1, 1, '2024-08-05', '08:00');
